openapi: 3.0.1

info:
  title: ANPR-integration-with-INAD
  description: "API rese disponibili da ANPR per integrazione con INAD."
  version: 1.0.0

servers:
- url: https://xxxxxx/ANPRIntegrationINAD/rest/v1.0.0

tags:
- name: utility

paths:
  /event_changed_digital_addresses:
    post:
      tags:
        - utility

      description: Ricevi evento delle variazioni intervenute nelle ultime 24h 

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/eventChangedDigitalAddresses'
            
      responses:
        200:
          description: OK
                        
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ack'

        400:
          description: "BAD REQUEST"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        401:
          description: "UNAUTHORIZED"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
       
        default:
          description: Gli HTTP state codes non indicati hanno un comportamento conforme alle indicazioni riportate in https://httpstatuses.com/
          content: {}


components:
  schemas:
    ack:
      type: string
      pattern: ^OK$
     
    eventChangedDigitalAddresses:
      required: 
        - referenceDate
        - resource

      type: object

      properties:
        referenceDate:
          description: data di riferimento dell'evento delle variazioni intervenute nelle ultime 24h 
          type: string      
          format: date

        resource:
          description: riferimento alla resource da recuperare
          type: string
          format: uri

      example:
        referenceDate: 2022-01-13
        resource:  changed_digital_addresses/2022-01-13

    Error:
      required:
      - timestamp
      - status
      - error
      - message
      - path
      type: object
      properties:
        timestamp:
          type: string
          description: timestamp dell'errore
          format: date-time
        status:
          maximum: 600
          minimum: 100
          type: integer
          description: HTTP status code generato per l'errore verificatosi
          format: int32        
        error:
          type: string
          description: Tipologia dell'errore verificatosi
        message:
          type: string
          description: Messaggio specifico per errore verificatosi
        path:
          type: string
          description: Riferimento al path per cui si è verificato l'errore  
        
      example:
        timestamp: 2020-05-05T10:55:18.383+0000
        status: 400
        error: BAD REQUEST
        message: Parametro assente
        path: /changed_digital_addresses
    
